### ISSUE TITLE
.rst file result precision question

### ISSUE THREAD

**Issue by xiaomaiAI** [pyansys/pymapdl-reader#53]
Hi,
    Is rst result datas store in float type? I took these datas compared with ANSYS solution, I found only 6 or 7 significant digits
are correct.  thanks.

**Comment by akaszynski** [comment]
In the header file describing Ansys resutls, `fdresu.inc`, there are detailed descriptions of each data type output from the result file.  It appears except for special cases, the result records are stored in double precision.

These header files are included in the unified install and can be found at:
```
.../ansys/customize/include/fdresu.inc
```
Path may vary on Windows.

---

Since I'm not using any of Ansys's post-processing routines in this module, it's possible that the difference you're seeing is due to variations in how we implemented certain routines.  For example, when computing the principal stress `ansys-mapdl-reader` uses `np.linalg._umath_linalg.eigvalsh_lo` for each 3x3 stress tensor, which may generate different results than Ansys's approach.  Same with euler angle rotations.
