### ISSUE TITLE
How to get the middle side nodal stress

### ISSUE THREAD

**Issue by xiaomaiAI** [pyansys/pymapdl-reader#7]
Hi,
  how can I get the middle side nodal stress from `.rst` file, the results always be `nan` from `plane183`. Thank you.

**Comment by akaszynski** [comment]
> Hi,
> how can I get the middle side nodal stress from `.rst` file, the results always be `nan` from `plane183`. Thank you.

MAPDL doesn't calculate stress values for mid-side notes, just for edge nodes.  I recommend interpolating these values from the edge nodes using another software package (perhaps pyvista's interpolation filter) if you'd like to get values at the mid-side notes.  Realize that the interpolation won't be perfect since it's not an averaged extrapolation as in the edge nodes.

For more details regarding the interpolation filter, see https://docs.pyvista.org/examples/01-filter/interpolate.html
